services:
  postgres:
    image: postgres:16
    container_name: postgres_test
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend_test

    ports:
      - "5434:5432"
